### ISSUE TITLE
Support Lightning URI's starting with `lightning:`

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-backend#102]
![image](https://user-images.githubusercontent.com/16877539/55561270-2a1b0900-56f2-11e9-8c29-8e378d2b4a67.png)

**Comment by michael1011** [comment]
I would simply trim the `lightning:` prefix in the frontend.

**Comment by kilrau** [comment]
Maybe some quick research on it's status to become a standard? If so we should treat it differently. Couldn't find anything in a quick search tho.
