### ISSUE TITLE
Proper handling of the RPC certificates of nodes

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-backend#13]
Right now we are hardcoding the certificates of the Docker images of BTCD, LTCD and LND which is fine for now but eventually I think it is reasonable to do it similar to [LND](https://github.com/lightningnetwork/lnd/blob/master/docker/btcd/Dockerfile) by letting the services generate their own certificates and mounting the folder of the certificates on the host machine.

**Comment by michael1011** [comment]
This is also closed by #34
