### ISSUE TITLE
bot features

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-backend#137]
- [x] `getaddress btc`, `getaddress ltc`
- [x] remote/local channel balance exhausted alerts. threshold configurable.
- [x] `withdraw x.x btc`, `withdraw x.x ltc` (fixed address) **OTP required**
- [x] high number of failed swaps from same IP - alert
- [x] `newaddress btc`, `newadress ltc` (includes above commands listing all addresses, indicating which ones were `(used)`. Sorted by top newest to bottom oldest.
- [x] `getlockedfunds btc`, `getlockedfunds ltc` 
- [x] `getpendingswaps` 
- [ ] `htlctimelockconfig <pairid> <timeout in minutes>`  **OTP required**
- [ ] `gethtlctimelockconfig`

All these commands should also have a CLI implementation, to avoid Discord as a single point of failure.

**Comment by peartobear** [comment]
Added `getlockedfunds btc` and `getlockedfunds ltc` which can help with querying the locked balances and toggle reverse swap on and off manually or automatically directly from the bot, last resort in case of reverse spam attack.

**Comment by michael1011** [comment]
Withdraw command was added by #142

**Comment by peartobear** [comment]
Added `getpendingswaps` command for better swap debugging

**Comment by peartobear** [comment]
Added `gethtlctimelockconfig` `htlctimelockconfig` and OTP requirements along with the requirement for adjacent CLI command to avoid a single point of failure (discord)
