### ISSUE TITLE
Rebalancing Boltz Channels

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-backend#185]
Monitor the need for a rebalancing of the existing Boltz channels via a discord bot command and throw alerts like:

`channel id: xx, inbound below the threshold by x sats`
`channel id: yy, outbound below the threshold by y sats`

Carefully track and adapt capacity assignments. In case of the need for rebalancing, do so manually by doing self routes, or by submarine swapping back to Boltz, or by paying exchanges that accept lightning ex: Bitfinex and withdrawing out from them. Explore options to automate trickle pay (1 sats periodically to public nodes to ping them that we still intend to keep the channel open)

**Comment by michael1011** [comment]
Closed by https://github.com/boltzexchange/channel-bot
