### ISSUE TITLE
prepay miner fee should be made atomic

### ISSUE THREAD

**Issue by ecdsa** [BoltzExchange/boltz-backend#202]
Currently the server accepts the miner fee payment regardless of whether it will receive the main payment. This leads to issues if no route is found for the main payment.

I believe the flow should be changed as follows:
1. client sends HTLCs for both invoices (`minerFeeInvoice` and `invoice`)
2. Server waits until he has received both HTLCs.
3. Once both HTLCs are received, the server fulfills the HTLC of `minerFeeInvoice` and it sends the onchain funds to the locking address. 
4. If (3.) is not satisfied and invoices time out, the server fails both HTLCs.
5. The rest of the flow is unchanged.

**Comment by ecdsa** [comment]
hi, was this fixed? in which commit?

**Comment by michael1011** [comment]
https://github.com/BoltzExchange/boltz-backend/pull/238
Was implemented as part of this PR

**Comment by SomberNight** [comment]
Was the security issue that @ecdsa reported on 2022-03-31 fixed? The PR predates that.

**Comment by ecdsa** [comment]
@SomberNight actually, the issue described here seems to be fixed. 
However, waiting for invoices to time out is nor acceptable in practice, see issue #278, which has not been fixed yet.
