### ISSUE TITLE
The regtest server not responding to the reverse-submarine swap preimage revelation

### ISSUE THREAD

**Issue by joemphilips** [BoltzExchange/boltz-backend#241]
Hi all.
An exchange I’m working now has a plan to support LN deposit/withdrawal for our customers.
But we don’t want to be a routing node (at least for now) since we want to start simple. So we are looking for the LN node which supports a submarine swap to maintain our channel balance.
We are planning to have one large private channel with the node and do all payment/receive on that channel.
So I’ve been making a basic tutorial to learn how to use boltz-backend as a submarine-swap service only for BTC. https://github.com/joemphilips/docker-lnd-handson
But I’m facing a problem, when I try to run a reverse-submarine swap against the server in a regtest environment, even after the client claims their on-chain HTLC by revealing its preimage, the server does nothing and the off-chain payment is frozen forever.
I was expecting that boltz server will check the on-chain tx, retrieve the preimage from it and receive the off-chain payment using that preimage automatically. Am I misunderstanding something?
You can reproduce the problem by running [the tutorial](https://github.com/joemphilips/docker-lnd-handson/blob/master/2-BOLTZ.md)

The version for boltz-backend is v2.4.3

**Comment by joemphilips** [comment]
By @michael1011 's help, I was able to avoid the problem by using a build from [this commit](https://github.com/BoltzExchange/boltz-backend/commit/a858a2f0be46c257bfe65ed07a25454fa3f2523a)
and by using RPC cookie instead of username/password pair for bitcoind.

I'm not sure I should close this issue since following problems are still need to be concerned.
1. Should boltz support rpcuser/password RPC auth or not?
2. If not, I suppose [the documentation](https://docs.boltz.exchange/en/latest/regtest/) should be updated.
3. The problem must be fixed in the latest release.

So I will leave it open.

**Comment by michael1011** [comment]
> Should boltz support rpcuser/password RPC auth or not?
> If not, I suppose the documentation should be updated.

I removed RPC user and password authentication because we didn't need it anymore in our deployments. I guess I can add it again. There is no real downside to it.

> The log could be improved in case the RPC is not working fine.

RPC already shows you errors when it can't connect. The ZMQ does not in some cases it seems. I will investigate that.
