### ISSUE TITLE
Add support for Liquid

### ISSUE THREAD

**Issue by matthiasdebernardini** [BoltzExchange/boltz-backend#250]
Bisq will start using liquid for its trades to dramatically reduce its fees, would be very useful to the community to be able to have a swap between liquid and LN. This would alleviate a lot of problems.

Sorry in advance if this is the wrong place to ask this.

**Comment by michael1011** [comment]
This is the right place!
Liquid support has been on our todo list for quite a while now. The fact that bisq is going to support it makes liquid even more interesting though.

**Comment by matthiasdebernardini** [comment]
:)
