### ISSUE TITLE
A transaction propagation delay causes "onchain coins could not be sent" error

### ISSUE THREAD

**Issue by yuyaogawa** [BoltzExchange/boltz-backend#298]
I set up two servers, lnd with neutrino and bitcoind on different VPS. Boltz-backend connects to them respectively. However, there is a transaction propagation delay between them that causes an error `"failureReason": "onchain coins could not be sent"` when a reverse swap is made. Below is the code this error happens.
```
    const response = await this.lndClient.sweepWallet(address, await this.getFeePerVbyte(satPerVbyte));

    return this.handleLndTransaction(response.txid, address, blockHeight);
  };

  private handleLndTransaction = async (transactionId: string, address: string, listStartHeight: number): Promise<SentTransaction> => {
    const rawTransaction = await this.chainClient.getRawTransactionVerbose(transactionId);
```

This error does not occur when lnd uses bitcoind with `txindex=1` and boltz-backend connects to them. I wonder if there is a way to fix this issue for my set up.

**Comment by michael1011** [comment]
> Have the transaction index enabled txindex=1

https://docs.boltz.exchange/en/latest/deployment/

The boltz backend explicitely requires the `txindex` to be enabled. It's not about propagation of the transaction but about the `this.chainClient.getRawTransactionVerbose` which calls the Bitcoin Core RPC and requires `txindex`

**Comment by yuyaogawa** [comment]
What I meant is I have LND with neutrino and Bitcoind with `txindex` enabled on different servers. When boltz-backend calls the Bitcoin Core RPC `this.chainClient.getRawTransactionVerbose`, it returns the error because the transaction that is broadcasted from LND is not yet propagated to the Bitcoind.

**Comment by yuyaogawa** [comment]
The instance I run LND has limited disk space. That's why I have to run another instance for Bitcoind. I added sleep function, but it does not solve the fundamental issue. Do you have any suggestions?

**Comment by michael1011** [comment]
> Do you have any suggestions?

That code snippet you sent in the first message assumes that the transcation was broadcasted through the Bitcoin Core node Boltz is connected to.

To fix that we have two options:
1. query the raw transaction that was sent not through Bitcoin Core but with the LND gRPC
2. you connect your LND to the Bitcoin Core running on the other instance

The first option could even be implemented as a fallback. But I'd prefer the second one, because I wouldn't use Neutrino in producton. What do you think?

**Comment by armurbalda** [comment]
Closing, since we don't want to optimize for Neutrino backend usage.
