### ISSUE TITLE
Payments to Phoenix fix

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-backend#329]
Payments to Phoenix mobile wallets currently fail if user doesn't have app open, because acinq node (which handles all payment to phoenix users) reports "channel temporary not available" which lnd in turn doesn't understand correctly and aborts payment trials.

One has to manually reset lnd's mission control via `lncli resetmc` and pay the invoice while user has wallet open to get payment through.

Ideas how approach this:
- take out some mc related config parameters that we still have
- smaller adjustments in backend how payments are sent
- test ourselves, if none of that helps - open lnd issue and automate `lncli resetmc`

**Comment by nymkappa** [comment]
Also having this issue. Using Phoenix as my main LN wallet, and boltz at least once a week I find it inconvenient to ask on nostr that my funds be manually pushed through my channels 😄.
