### ISSUE TITLE
Create swap RPC command stuck

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-backend#33]
Sometimes the gRPC command `createSwap` is stuck and has to be restarted to work

**Comment by peartobear** [comment]
Chrome dev tool shows following error:

![screen shot 2018-12-27 at 6 46 51 am](https://user-images.githubusercontent.com/44926540/50459310-f5860b80-09a4-11e9-85dd-1839d6ccc30d.png)

**Comment by michael1011** [comment]
This was related to BTCD/LTCD and was fixed by #85
