### ISSUE TITLE
Find solution for fee estimation

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-backend#36]
LTCD does not support the [`estimateFee`](https://godoc.org/github.com/btcsuite/btcd/rpcclient#Client.EstimateFee) method of BTCD. I discovered this in #35 and just hardcoded a fee of 10 sat per vbyte to avoid `not implemented` errors by LTCD.

Now we have to find a way to estimate a fee to use. I can think of two possible solutions:
- use another full node implementation that has fee estimation methods for BTC and LTC. And since that full node implementation has to be compatible with LND the only option is Bitcoin Core and Litecoin Core
- implement our own fee estimation tool by iterating over the transaction in the latest blocks and in the mempool to determine a reasonable fee

(Or we could simply not care about fees in Litecoin since the blocks are never full but that is not a long term solution.)

What do you think? @ImmanuelSegol @peartobear

**Comment by peartobear** [comment]
Second option seems more reasonable to me. Iterating over the latest blocks and the mempool txs and taking the average fee will solve this issue.

**Comment by peartobear** [comment]
The Bitcoin network fee gets too high at occasions which makes the minimum amount of swap impractical, building a robust fee estimation technique and using it to dynamically adjust the maximum-minimum-amount threshold is an important exploration vector

**Comment by michael1011** [comment]
https://mempool.space fixes this and is already implemented
