### ISSUE TITLE
Change Lightning Invoice+BIP21 Memo to "Boltz" to preserve privacy

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-backend#371]
In order for users to have it easier to connect swap transactions in their wallets with swaps in the Boltz's swap history, I propose to add Boltz's SwapID to the invoice and BIP21 descriptions:

Normal Swap Invoice: `Send to BTC Lightning` -> `Sent to Lightning (Boltz SwapID: {id})`
Reverse Swap BIP21: `Send to BTC address` -> `Sent to Bitcoin (Boltz SwapID: {id})`

Previous issue: https://github.com/BoltzExchange/boltz-backend/issues/136

**Comment by kilrau** [comment]
[Users just requested](https://twitter.com/openoms/status/1725545735582621961) to remove information where (which chain/network) the swap is going from invoice description to preserve privacy against e.g. an exchange. It's a valid request and for the BIP21 it suffices too.

Normal Swap Invoice: `Send to BTC Lightning` -> `Boltz Swap {id}`
Reverse Swap BIP21: `Send to L-BTC address` -> `Boltz Swap {id}`

**Comment by openoms** [comment]
Thanks for discussing this already. Agree with the comment above. Paying Boltz already implies that it is for a swap so it makes sense to include a swap ID to help the users, but should avoid sharing any more information in the memo.

**Comment by kilrau** [comment]
That was my thought, but @michael1011 just made me aware that we are allowing querying lockup transaction via swapid: https://docs.boltz.exchange/v/api/api#swap-status. So we shouldn't add the id, `Boltz` it is I guess.

**Comment by kilrau** [comment]
Substituted by https://github.com/BoltzExchange/boltz-backend/issues/445
