### ISSUE TITLE
Pair hash changes when there were no fee changes

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#390]
[Web App will do a double check to be safe](https://github.com/BoltzExchange/boltz-web-app/issues/197), but since we should expect integrations (of especially liquid wallets that are currently in the works) face the same issue - why does the liquid pair hash change if in fact nothing changed - this really should be fixed on backend side. I remember we determined it's difficult to do but I don't remember why anymore.

Liquid pair has a separate hash so it should be possible to not change liquid pair hash when mainchain fees changed:
![image](https://github.com/BoltzExchange/boltz-backend/assets/19181985/3611d76a-8598-44aa-9577-c36e9446af1e)

**Comment by kilrau** [comment]
Just discussed this Michael. Tl;dr: we agreed that status quo is not ideal but couldn't settle on sth right now, because it's not trivial to fix the issue while continue supporting our current 3 layer `type`, `pairId`, `orderSide` structure. See [docs](https://docs.boltz.exchange/v/boltz-backend-1/api#creating-normal-submarine-swaps):
![image](https://github.com/BoltzExchange/boltz-backend/assets/19181985/70b613e3-af18-4771-9be8-af24d2a7f500)

In short: the pairhash of Liquid/Lightning changes because "Lightning" under the Ticker `BTC` also includes mainchain. And mainchain fees change all the time. So we could either go all complicated by adding yet more hashes inside these pairs for the types `submarine` or `reversesubmarine` or, because we already know we'll be adding the types `submarine-taproot` and `reversesubmarine-taproot` soon,  having min 4 additional hashes inside one pair makes things even worse, think about a new API version.

A new API version also makes sense because in general we would do good in moving to pure `pairId` + `orderSide` and remove `type` - in line with exchange APIs and just so much easier to understand. Since we want to remove `type` there can be one type only and it should be all taproot.

So far my thoughts.

**Comment by michael1011** [comment]
Fixed in API v2
