### ISSUE TITLE
Fee strategy

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-backend#44]
The business model of Boltz providers is to charge fees on every swap. But how should that be done? Solely via the rate or with an extra parameter for `CreateSwap` and `CreateReverseSwap` that adds a specific amount to the funds the user should send?

Also: should there be a flat fee for every swap, a fee in percent or both?

**Comment by peartobear** [comment]
We also have to take volatility into account while designing this. Also, keeping in mind that future releases might have a Transferwise-like layout [See picture]. We should go down the abstraction root as much as possible. I'd say adding an extrea `fee` parameter that is `optional` for now should be right way forward and help us stay below a layer of abstraction. Referring to our previous discussion regarding volatility, there will be additional markup fee added to hedge against that, so integrating everything into rate doesn't make sense to me. 

![screen shot 2019-01-07 at 12 43 13 pm](https://user-images.githubusercontent.com/44926540/50749497-25bd8c00-127a-11e9-907c-a1f8e4f15b93.png)

**Comment by armurbalda** [comment]
also check how fees are currently represented internally. atm it's all LTC.

**Comment by michael1011** [comment]
@armurbalda hod did you come to that conclusion?
