### ISSUE TITLE
APIv2

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#443]
A collection of things to change in v2:

- [x] refactor `/nodestats` as per https://github.com/BoltzExchange/boltz-backend/issues/386#issuecomment-1752142975
- [x] move to [swagger](https://blog.logrocket.com/documenting-express-js-api-swagger/)
- [x] Move from `pair/swaptype/orderside` to `swaptype/from=asset,to=asset`. @michael1011 had strong arguments against my previous idea to eliminate `swaptype` (api flows are very different for every swaptype and different flows with very different parameters shouldn't be mingled into one endpoint) and proposed this solution which instead combines `pair`+`orderside` to `from=asset,to=asset`. Meets the goal of reducing 3 to 2 and easier to understand than `buy`/`sell` too.
- [x] Related to above: pairhash of any pair should only change if network fees actually changed, see https://github.com/BoltzExchange/boltz-web-app/issues/197, meaning for this exact combination `/swaptype/from=asset,to=asset`
- [x] Right now failure reason switches from `X less than expected Y` to `onchain HTLC timed out` if the timeout was reached. Backend should never overwrite the original failure reason. As part of APIv2, backend should change behavior.
- [ ] ~`transaction.refunded` -> `swap.claimExpired`~

**Comment by michael1011** [comment]
Started in #451 451
