### ISSUE TITLE
Reverse Swaps: Store Direct Addresses into routing hints of invoice

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#460]
Successor of https://github.com/BoltzExchange/boltz-backend/issues/455 (which is an undocumented temporary feature): we want to enable a more robust way of setting a "direct address" by storing it in the routing hints table of an invoice instead of poluting the invoice memo.

What are Direct Addresses? A direct address of e.g. a Liquid Reverse Swap is a new Liquid Address of the underlying liquid wallet that the sender *can* optionally use instead of paying the swap invoice if his wallet is on Liquid too. For the famous use case of Aqua to Aqua payments, this then results in a much cheaper plain Liquid transfer instead of a Liquid -> Lightning -> Liquid swap. Should work for all supported chains.

**Comment by michael1011** [comment]
Closed by #482
