### ISSUE TITLE
Covenants: Trustless Refunds for Chain Overpayments

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#464]
## Goal
A Boltz API client should only be able to claim the previously agreed upon swap amount, if a user accidentally overpays. Client can then throw "you overpaid, enter your refund address here" which triggers refund path for overpaid amount.

This is possible using covenants in Liquid Normal Swaps.

**Comment by dni** [comment]
yeah, this is awesome!
