### ISSUE TITLE
Network fee on testnet very high

### ISSUE THREAD

**Issue by jomagalo** [BoltzExchange/boltz-backend#476]
The network rate of the btc/ln pair seems very high to me between 8 and 10k sat. How can this be established?

Thank

**Comment by michael1011** [comment]
In your config here: https://github.com/BoltzExchange/boltz-backend/issues/473#issuecomment-1919382875

````toml
  # Optional API endpoint of a MempoolSpace instance running on the chain of the configured client
  mempoolSpace = "https://mempool.space/api"
```

You are using the *mainnet* mempool.space instance
