### ISSUE TITLE
Add other currencies

### ISSUE THREAD

**Issue by jomagalo** [BoltzExchange/boltz-backend#479]
Is it possible to add other currencies such as ltc and usdt?

Thank!!

**Comment by michael1011** [comment]
Technically the backend could support:
- all chains that have node software forked from a relatively recent Bitcoin Core version
- Liquid tokens
- Tokens on EVM chains

But we are not actively developing those things

**Comment by jomagalo** [comment]
Can you indicate some configuration example to add a liquid token or asset pair to boltz.conf?

The documentation does not provide anything in this regard.

Thank you

**Comment by michael1011** [comment]
It is technically possible, but currently we do not support any other Liquid token than L-BTC
