### ISSUE TITLE
Fail /swap/submarine calls with short invoice expiries

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#490]
For integrations we can't be sure about client-side checks like https://github.com/BoltzExchange/boltz-web-app/issues/359, so backend should return an error and fail the swap creation if amount above 0-conf threshold and invoice expiry <2 block times, e.g.
- mainchain swaps if invoice expiry is <20 mins
- liquid swaps and invoice expiry <2mins

**Comment by michael1011** [comment]
Closed by https://github.com/BoltzExchange/boltz-backend/pull/498
