### ISSUE TITLE
Bug: Aqua reverse swap request - "Send to L-BTC address" in invoice description

### ISSUE THREAD

**Issue by salvatoto** [BoltzExchange/boltz-backend#496]
When creating reverse swaps from Aqua app, even if I don't include the `address` nor `addressSig` parameters in the request, we're getting back an invoice with "Send to L-BTC address" in the `description`. 

example:
lnbc10u1pj7ged4sp54rrg70kch58y6afg7tcqcvykzkxzvumpyktmsdmmejg5knlkfutqpp5psxh7rqqzdqzeqdnpfxamy2h60mn0zvdrgf4q69t6qrutlju7d5qdpz2djkuepqw3hjqnpdgf2yxgrpv3j8yetnwvxqyp2xqcqz959qxpqysgqcarn0n8404ky4tjzyxe4u4n22q94at6pp3fagnhka8wnah9jzykkml4674jfe5eupvjvkke4f7y74rcd06fkp3qt0x62wfk6vu4xplcqr0yx9a

**Comment by michael1011** [comment]
That behaviour is expected and the memo has always been that
