### ISSUE TITLE
Liquid: Covenant Refunds for overpaid amounts

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#528]
We want to enable users that sent too much L-BTC in a Liquid-to-Lightning or Liquid-to-Chain swap to be able to claim refunds for the overpaid amount themselves using covenants. Refund address will be provided in the refund step, just as-is.

**Comment by kilrau** [comment]
Just leaving a comment here that I manually refunded a couple of overpaid liquid swaps recently and logs show that some of the users actually tried to refund themselves via our web app (but it failed with `Not creating partial signature for refund of Chain Swap ABC: it is not eligible {"level":"verbose"}`). Meaning we can expect most users that accidentally overpaid to try refund themselves, worst case we just point them at it - still a lot less work than refunding manually.

So this feature is significant for reducing support volume.

**Comment by michael1011** [comment]
Closed #599
