### ISSUE TITLE
Feature suggest: Extend CLN mpay plugin to be able to pay bolt12 invoices

### ISSUE THREAD

**Issue by urza** [BoltzExchange/boltz-backend#565]
Mpay plugin is awesome, I have 100% success rate with it, whereas the default CLN pay fails all the time.

But mpay can only pay bolt11 invoices, so when I pay to botl12 offer and fetch invoice from remote node, that is bolt12 invoice instead of bolt11 invoice and mpay can't pay those and I am back to default CLN pay :(

**Comment by kilrau** [comment]
Thanks, glad you are happy! Still use mpay with a bit of caution though, it is not "battle tested".

As mpay was built for us internally and Bolt12 is not relevant for our own use case (yet) please don't expect to see this feature in TwoWeeksTM

**Comment by kilrau** [comment]
We went live with Bolt12 using CLN's regular `pay` today and will not extend mpay anymore as `xpay` (which will fix **everything**) is on the horizon.
