### ISSUE TITLE
Keep failure reason when changing swap error state to `swap.expired`

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#616]
We are currently changing swap states `transaction.lockupFailed` and `transaction.failed` to `swap.expired` after a swap's timeout passed. We want to keep the original failure reason to hint on why the swap expired. It's useful information if the user e.g. sent too little (`locked X is less than expected Y`) vs. nothing (`onchain HTLC timed out`).

**Comment by michael1011** [comment]
Closed by #621
