### ISSUE TITLE
Webhooks: filter status updates

### ISSUE THREAD

**Issue by dangeross** [BoltzExchange/boltz-backend#624]
It could be advantageous to optionally filter which swap update statuses a webhook wishes to receive (either by include or exclude list, can be discussed)

For example, if a webhook service is serving push notifications to mobile devices, we only really want to send the essential swap statuses to the device (statuses that trigger a claim or refund after verification). Ideally this is to prevent notification spam, as each OS forces an application to show notification content for each push message received and processed.

**Comment by kilrau** [comment]
I'd vouch for an include list
