### ISSUE TITLE
Chain/Submarine Swaps: Continue watching chain after a tx was dropped from mempool

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-backend#674]
Today I discovered an interesting edge case that we are not handling correctly:
1. User sends bitcoin transaction into the swap
2. Transaction disappears from the mempool (whatever the reason)
3. Backend notices this (`Could not find unconfirmed BTC user lockup transaction of Chain Swap ABC: No such mempool or blockchain transaction. ID: xyz` and looks like backend stops watching the chain after this
4. User sends new transaction into lockup way within expiry limit
5. Swap expires because backend never knew about the new tx. Refund doesn't work.

**Comment by michael1011** [comment]
Can't reproduce this. Let's reopen it when we have another case to debug
