### ISSUE TITLE
Show user timeout for the swap

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-backend#69]
Currently swaps can only be refunded if and when the transaction gets atleast one confirmation. Allow transactions to be refunded from mempool as well for smoother UX

**Comment by michael1011** [comment]
@peartobear sorry for the confusion but we cannot refund swaps in the mempool since the timelock has to expire first. What I meant showing to the user that the transaction was found in the mempool and that he has to wait for a certain number of blocks

**Comment by peartobear** [comment]
Find a solution and also explain how we do it in the FAQs as well.

**Comment by armurbalda** [comment]
New webapp will allow user to submit refund at any time, replaced by https://github.com/BoltzExchange/boltz-backend/issues/325
