### ISSUE TITLE
Fix fee rate estimation

### ISSUE THREAD

**Issue by L0laL33tz** [BoltzExchange/boltz-backend#759]
Boltz fee rate is consistently below the recommended minimum fees both by mempool and whatthefee.io, making swaps take hours to confirm... pls fix kind sers (╥_╥)

**Comment by michael1011** [comment]
We use the highest mempool.space `fastestFee` fee estimation from multiple instances multiplied by 1.1 and refreshed every 2.5 minutes. That *should* always confirm in a block or two. Did that confirmation behaviour change for you recently? How often did a transaction not confirm in a timely manner?

**Comment by kilrau** [comment]
If you are up to send us some samples (e.g. swap or tx id) via support chat @ boltz.exchange we can check if our estimations were correct @L0laL33tz
